name: codelessly_interview
description: Simple painters and interaction demonstration.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # default
  cupertino_icons: ^0.1.3

  # preferences
  hive: ^1.4.2
  hive_flutter: ^0.3.1
  shared_preferences: ^0.5.10

  # development
  flutter_screenutil: ^2.3.1
  uuid: ^2.2.0
  conditional_builder: ^1.0.2
  bot_toast: ^3.0.1
  auto_route: ^0.6.7
  flutter_webview_plugin: ^0.3.11
  permission_handler: ^5.0.1+1
  cached_network_image: ^2.2.0+1
  carousel_slider: ^2.2.1
  google_fonts: ^1.1.0
  flutter_svg: ^0.18.1
  url_launcher: ^5.7.2
  simple_animations: ^2.2.1
  visibility_detector: ^0.1.5
  keyboard_visibility: ^0.5.6


  # State Management
  get_it: ^4.0.4
  injectable: ^1.0.2
  flutter_bloc: ^6.0.5
  freezed_annotation: ^0.11.0+1
  json_serializable: ^3.4.1

  # ui
  dotted_border: ^1.0.6
  auto_size_text: ^2.1.0
  flutter_spinkit: ^4.1.2+1
  flutter_page_transition: ^0.1.6
  avatar_glow: ^1.2.0
  snapping_sheet: ^2.0.1
  animate_do: ^1.7.3

  # features

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^0.7.1
  build_runner:
  injectable_generator: ^1.0.3
  auto_route_generator: ^0.6.7
  freezed: ^0.11.6

flutter:
  uses-material-design: true
  # assets:
    # assets-generator-begin
    # assets-generator-end
  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
